blueprint:
  name: Media Player Song Change Action with TagTuner Availability
  description: Sends the media_artist, media_title, and media_player to a defined action whenever the media_title changes on the selected media_player. Includes a TagTuner device and ensures it is available.
  domain: automation
    media_player:
      name: Media Player
      description: The media player to monitor for song changes.
      selector:
        entity:
          filter:
            - integration: music_assistant
    action_service:
      name: Action Service
      description: The ESPHome service to call with media_artist, media_title, media_player, and TagTuner as data.
      default: esphome.esphome_tagreader2_set_media_info

trigger:
  - platform: state
    entity_id: !input media_player
    attribute: media_title

action:
  - service: !input action_service
    data:
      artist: "{{ state_attr(trigger.entity_id, 'media_artist') }}"
      title: "{{ state_attr(trigger.entity_id, 'media_title') }}"
      player: "{{ input.media_player }}"
